<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-lavender dark:text-cream leading-tight">
            {{ __('Notifications') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-3xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="flex justify-between items-center mb-6">
                        <h3 class="text-lg font-semibold text-[#8D77AB]">All Notifications</h3>
                        <form action="{{ route('notifications.markAllAsRead') }}" method="POST">
                            @csrf
                            <button type="submit" class="text-sm text-[#8D77AB] hover:underline">Mark all as read</button>
                        </form>
                    </div>

                    <div class="space-y-4">
                        @forelse ($notifications as $notification)
                            <div class="p-4 rounded-lg {{ $notification->read ? 'bg-white' : 'bg-[#E1EACD]/30' }} border border-gray-200">
                                <div class="flex items-start">
                                    <div class="flex-shrink-0 mr-3">
                                        @if($notification->type == 'like')
                                            <svg class="w-6 h-6 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd"></path>
                                            </svg>
                                        @elseif($notification->type == 'comment')
                                            <svg class="w-6 h-6 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M18 10c0 3.866-3.582 7-8 7a8.841 8.841 0 01-4.083-.98L2 17l1.338-3.123C2.493 12.767 2 11.434 2 10c0-3.866 3.582-7 8-7s8 3.134 8 7zM7 9H5v2h2V9zm8 0h-2v2h2V9zM9 9h2v2H9V9z" clip-rule="evenodd"></path>
                                            </svg>
                                        @elseif($notification->type == 'connection')
                                            <svg class="w-6 h-6 text-green-500" fill="currentColor" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
                                            </svg>
                                        @else
                                            <svg class="w-6 h-6 text-[#8D77AB]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15
                                                <path stroke-linecap="round"